import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';

/**
 * Harness adapters.
 *
 * Each supported harness gets one generated `opencontract` entry Skill that
 * delegates to the installed system entry Action. Generated files carry an
 * ownership marker so `init` and `update` replace only what OpenContract wrote
 * and never overwrite a file a user authored at the same path.
 */

export const GENERATED_MARKER = '<!-- opencontract:generated -->';

export interface HarnessAdapter {
  readonly name: string;
  /** Path of the generated entry Skill, relative to the workspace root. */
  readonly relativePath: string;
}

/** The harnesses v1 supports. Adding one is a new entry, not a code change. */
export const SUPPORTED_HARNESSES: readonly HarnessAdapter[] = [
  { name: 'codex', relativePath: '.codex/skills/opencontract/SKILL.md' },
  { name: 'claude', relativePath: '.claude/skills/opencontract/SKILL.md' },
  { name: 'cursor', relativePath: '.cursor/skills/opencontract/SKILL.md' },
];

export function adapterFor(harness: string): HarnessAdapter | undefined {
  return SUPPORTED_HARNESSES.find((entry) => entry.name === harness);
}

/**
 * Render a harness entry Skill. The body points at the system entry Action
 * rather than restating the Action catalog, so a system update changes behavior
 * without regenerating adapters.
 */
export function renderAdapter(harness: string, systemRelativePath: string): string {
  const entrySkill = `${systemRelativePath}/actions/opencontract/SKILL.md`;
  return `${GENERATED_MARKER}
---
name: opencontract
description: Entry point for OpenContract agent-driven work; discovers and delegates to installed Actions.
metadata:
  version: v1.0.0
  harness: ${harness}
---

# OpenContract

This file is generated by OpenContract. Edits will be replaced on the next
\`opencontract update\`. To customize behavior, edit the system entry Action or
add a project Action under \`.opencontract/actions/\`.

## How to use

Load the system entry Skill and follow it:

\`\`\`text
${entrySkill}
\`\`\`

It enumerates the installed Actions and Contracts and hands off to the one that
fits the work. This adapter intentionally holds no Action logic of its own.

## Commands

- \`opencontract action list\` — installed Actions with exact versions
- \`opencontract contract list\` — installed Contracts with exact versions
- \`opencontract validate <path>\` — validate an Artifact or directory
- \`opencontract validate-action <dir>\` — validate a tracked ActionRun
- \`opencontract doctor\` — report workspace health
`;
}

/** True when the file at `path` was generated by OpenContract. */
export function isGenerated(path: string): boolean {
  if (!existsSync(path)) return false;
  // The marker is on the first line so this stays a cheap check.
  const head = readFileSync(path, 'utf-8').slice(0, GENERATED_MARKER.length + 2);
  return head.startsWith(GENERATED_MARKER);
}

export type AdapterWriteOutcome =
  | { readonly kind: 'written'; readonly path: string }
  | { readonly kind: 'unsupported'; readonly harness: string }
  | { readonly kind: 'conflict'; readonly path: string };

/**
 * Write one harness adapter. An existing unmarked file at the target path is a
 * conflict: it was authored by someone, so it is left untouched and reported
 * for a human to resolve.
 */
export function writeAdapter(
  workspaceRoot: string,
  harness: string,
  systemRelativePath: string,
): AdapterWriteOutcome {
  const adapter = adapterFor(harness);
  if (!adapter) {
    return { kind: 'unsupported', harness };
  }

  const target = join(workspaceRoot, adapter.relativePath);
  if (existsSync(target) && !isGenerated(target)) {
    return { kind: 'conflict', path: target };
  }

  mkdirSync(dirname(target), { recursive: true });
  writeFileSync(target, renderAdapter(harness, systemRelativePath), 'utf-8');
  return { kind: 'written', path: target };
}
