import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { OpenContractError } from '../domain/errors.js';
import { discoverWorkspace } from './discovery.js';

/**
 * Initialize a new OpenContract workspace in the target directory.
 * Creates the required directory structure, default configuration, and
 * placeholder manifest. Does not overwrite an existing workspace.
 */
export function initWorkspace(targetDir: string, options: { harnesses?: string[] } = {}): void {
  // Check if workspace already exists
  if (discoverWorkspace(targetDir)) {
    throw new OpenContractError(
      'WORKSPACE_EXISTS',
      'An OpenContract workspace already exists at this location.',
      { path: targetDir },
    );
  }

  const harnesses = options.harnesses ?? ['codex', 'claude', 'cursor'];

  // Create directory structure
  const dirs = [
    '.opencontract',
    '.opencontract/system',
    '.opencontract/cache',
    '.opencontract/actions',
    '.opencontract/contracts',
    'opencontract',
    'opencontract/specs',
    'opencontract/artifacts',
    'opencontract/artifacts/archive',
  ];

  for (const dir of dirs) {
    const fullPath = join(targetDir, dir);
    if (!existsSync(fullPath)) {
      mkdirSync(fullPath, { recursive: true });
    }
  }

  // Write default configuration
  const configPath = join(targetDir, '.opencontract', 'config.yaml');
  if (!existsSync(configPath)) {
    const defaultConfig = generateDefaultConfig(harnesses);
    writeFileSync(configPath, defaultConfig, 'utf-8');
  }

  // Write placeholder system manifest
  const manifestPath = join(targetDir, '.opencontract', 'system', 'manifest.yaml');
  if (!existsSync(manifestPath)) {
    const placeholderManifest = generatePlaceholderManifest();
    writeFileSync(manifestPath, placeholderManifest, 'utf-8');
  }

  // Create harness adapter directories (actual adapters will be generated by update)
  for (const harness of harnesses) {
    const harnessDir = join(targetDir, `.${harness}`, 'skills', 'opencontract');
    mkdirSync(harnessDir, { recursive: true });
  }
}

function generateDefaultConfig(harnesses: string[]): string {
  return `# OpenContract workspace configuration
# Paths are relative to the workspace root (parent of .opencontract/)

# System-owned definition tree
system: .opencontract/system

# Cached exact-version definitions
cache: .opencontract/cache

# Project-owned Action and Contract extensions
projectActions: .opencontract/actions
projectContracts: .opencontract/contracts

# Canonical specifications and managed artifacts
specs: opencontract/specs
artifacts: opencontract/artifacts
archive: opencontract/artifacts/archive

# Local registries (optional)
registries: []

# Trust configuration for semantic validators
trust:
  validatorRoots:
    - .opencontract/system

# Validator subprocess configuration
validator:
  pythonExecutable: python3
  timeoutMs: 30000
  maxOutputBytes: 1048576

# Definition source overrides (optional)
overrides:
  actions: {}
  contracts: {}

# Selected harness adapters
harnesses: [${harnesses.map((h) => `"${h}"`).join(', ')}]
`;
}

function generatePlaceholderManifest(): string {
  const now = new Date().toISOString();
  return `# OpenContract system manifest
# This file is managed by 'opencontract update'

version: "1.0.0"
installedAt: "${now}"
actions: []
contracts: []
`;
}

/**
 * Check if a workspace is properly initialized by verifying required paths exist.
 */
export function isWorkspaceInitialized(workspaceRoot: string): boolean {
  const requiredPaths = [
    '.opencontract/config.yaml',
    '.opencontract/system',
    'opencontract/specs',
    'opencontract/artifacts',
  ];

  return requiredPaths.every((path) => existsSync(join(workspaceRoot, path)));
}
