import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { cpSync, mkdirSync, mkdtempSync, rmSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { bundledSystemRoot } from '../../src/resources.js';
import { migrateToGlobalSystem } from '../../src/system/migration.js';
import { runScopedUpdate } from '../../src/system/update-scoped.js';
import { discoverWorkspace, resolvePaths } from '../../src/workspace/discovery.js';
import { DefinitionResolver } from '../../src/definitions/resolver.js';
import { GENERATED_MARKER } from '../../src/system/harnesses.js';

describe('Integration: v1.0 to v1.1 migration', () => {
  let tempDir: string;
  let home: string;
  let projectRoot: string;

  beforeEach(() => {
    tempDir = mkdtempSync(join(tmpdir(), 'opencontract-integration-migration-'));
    home = join(tempDir, 'home');
    projectRoot = join(tempDir, 'project');
    mkdirSync(home, { recursive: true });
    mkdirSync(projectRoot, { recursive: true });
  });

  afterEach(() => {
    rmSync(tempDir, { recursive: true, force: true });
  });

  /** A realistic v1.0.0 project: local system tree, local cache, legacy adapter. */
  function createV1Project() {
    for (const dir of [
      '.opencontract/actions',
      '.opencontract/contracts',
      '.opencontract/cache/1.0.0',
      'opencontract/specs',
      'opencontract/artifacts',
    ]) {
      mkdirSync(join(projectRoot, dir), { recursive: true });
    }

    // Real bundled system so definitions actually resolve after migration.
    cpSync(bundledSystemRoot(), join(projectRoot, '.opencontract', 'system'), { recursive: true });
    writeFileSync(join(projectRoot, '.opencontract', 'cache', '1.0.0', 'marker.txt'), 'cached\n');

    writeFileSync(
      join(projectRoot, '.opencontract', 'config.yaml'),
      `system: .opencontract/system
cache: .opencontract/cache
projectActions: .opencontract/actions
projectContracts: .opencontract/contracts
specs: opencontract/specs
artifacts: opencontract/artifacts
archive: opencontract/artifacts/archive
trust:
  validatorRoots:
    - .opencontract/system
validator:
  pythonExecutable: python3
  timeoutMs: 30000
harnesses: ["claude"]
`,
    );

    // Legacy single-entry adapter, generated by v1.0.
    mkdirSync(join(projectRoot, '.claude', 'skills', 'opencontract'), { recursive: true });
    writeFileSync(
      join(projectRoot, '.claude', 'skills', 'opencontract', 'SKILL.md'),
      `${GENERATED_MARKER}\n---\nname: opencontract\n---\n\nLegacy entry.\n`,
    );
  }

  it('migrates end to end and leaves the project working', () => {
    createV1Project();

    const result = migrateToGlobalSystem({ projectRoot, home });

    expect(result.needed).toBe(true);
    expect(result.success).toBe(true);

    // Global system installed
    expect(existsSync(join(home, '.opencontract', 'system', 'manifest.yaml'))).toBe(true);

    // Cache merged upward
    expect(existsSync(join(home, '.opencontract', 'cache', '1.0.0', 'marker.txt'))).toBe(true);
    expect(result.cacheMerged).toContain('1.0.0');

    // Config rewritten, unrelated fields preserved
    const config = readFileSync(join(projectRoot, '.opencontract', 'config.yaml'), 'utf-8');
    expect(config).toContain('system: ~/.opencontract/system');
    expect(config).toContain('cache: ~/.opencontract/cache');
    expect(config).toMatch(/-\s*~\/\.opencontract\/system/);
    expect(config).toContain('pythonExecutable: python3');
    expect(config).toContain('specs: opencontract/specs');

    // Backup taken, local tree gone
    expect(result.backupPath).toBeDefined();
    expect(existsSync(join(result.backupPath!, 'manifest.yaml'))).toBe(true);
    expect(existsSync(join(projectRoot, '.opencontract', 'system'))).toBe(false);

    // Legacy adapter removed, per-Action adapters generated
    expect(existsSync(join(projectRoot, '.claude', 'skills', 'opencontract'))).toBe(false);
    expect(existsSync(join(projectRoot, '.claude', 'commands', 'oc'))).toBe(true);
    expect(existsSync(join(projectRoot, '.claude', 'skills', 'oc-explore', 'SKILL.md'))).toBe(true);
  });

  it('resolves definitions from the global system after migration', () => {
    createV1Project();
    migrateToGlobalSystem({ projectRoot, home });

    // resolvePaths expands ~/ against the real home, so assert against the
    // migrated config text plus the global tree the migration produced.
    const workspace = discoverWorkspace(projectRoot);
    expect(workspace!.config.system).toBe('~/.opencontract/system');

    const globalSystem = join(home, '.opencontract', 'system');
    const resolver = new DefinitionResolver(
      {
        root: projectRoot,
        configPath: join(projectRoot, '.opencontract', 'config.yaml'),
        system: globalSystem,
        cache: join(home, '.opencontract', 'cache'),
        projectActions: join(projectRoot, '.opencontract', 'actions'),
        projectContracts: join(projectRoot, '.opencontract', 'contracts'),
        specs: join(projectRoot, 'opencontract', 'specs'),
        artifacts: join(projectRoot, 'opencontract', 'artifacts'),
        archive: join(projectRoot, 'opencontract', 'artifacts', 'archive'),
        registries: [],
        trustedValidatorRoots: [globalSystem],
      },
      workspace!.config,
    );

    expect(resolver.listActions().length).toBeGreaterThan(0);
    expect(resolver.listContracts().length).toBeGreaterThan(0);
  });

  it('is idempotent — a second run reports nothing to do', () => {
    createV1Project();
    migrateToGlobalSystem({ projectRoot, home });

    const second = migrateToGlobalSystem({ projectRoot, home });

    expect(second.needed).toBe(false);
    expect(second.success).toBe(true);
  });

  it('auto-migrates through update run inside the project', () => {
    createV1Project();

    const result = runScopedUpdate({ projectRoot, home, project: true });

    expect(result.success).toBe(true);
    expect(result.projectResult?.migration?.needed).toBe(true);
    expect(result.projectResult?.migration?.backupPath).toBeDefined();
    expect(existsSync(join(projectRoot, '.claude', 'commands', 'oc'))).toBe(true);
  });

  it('keeps the backup so the old tree can be inspected', () => {
    createV1Project();

    const result = migrateToGlobalSystem({ projectRoot, home });

    const backupActions = join(result.backupPath!, 'actions');
    expect(existsSync(backupActions)).toBe(true);
  });
});
